name: Update Torn Stats
on:
  schedule:
    - cron: '0 * * * *' # This runs every hour. 
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pillow requests

      - name: Run update script
        env:
          TORN_API_KEY: ${{ secrets.TORN_API_KEY }}
        run: python update_stats.py

      - name: Commit and push changes
        run: |
          git config --global user.name "StatBot"
          git config --global user.email "bot@github.com"
          git add xans_counter.jpg
          git commit -m "Update Xanax stats" || exit 0
          git push
